# Generated by Django

from django.db import migrations


def create_default_roles(apps, schema_editor):
    """Create default roles (Admin, Manager, Employee, etc.) for RBAC."""
    Group = apps.get_model('auth', 'Group')
    
    roles = ['Admin', 'Manager', 'Employee', 'Technician', 'Viewer']
    for role in roles:
        Group.objects.get_or_create(name=role)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_roles),
    ]